name: Verify Format

on: pull_request

jobs:
  check-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.17]
        otp: [26.0]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v4
        id: mix-cache-format
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install mix dependencies
        if: steps.mix-cache-format.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: Verify FORMATTER
        run: mix format --check-formatted